/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Yuri.Ramos
 */
public class Mainwindow extends javax.swing.JFrame {
    
    private MoviesPanel movies_panel;
    private SearchPanel search_panel;
    private ByJsonPanel by_json_panel;
    
    /**
     * Creates new form mainwindow
     */
    public Mainwindow() {
        initComponents();
        setIconsToForms();      
        
        this.jPanelPrincipal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        MoviesButton = new javax.swing.JButton();
        PersonButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        MoviesLabel = new javax.swing.JLabel();
        PersonLabel = new javax.swing.JLabel();
        SearchLabel = new javax.swing.JLabel();
        ByJsonLabel = new javax.swing.JLabel();
        ByJsonButton = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        MoviesButton.setText("Movies");
        MoviesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesButtonActionPerformed(evt);
            }
        });

        PersonButton.setText("Person");
        PersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        ByJsonButton.setText("By Json");
        ByJsonButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ByJsonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByJsonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(PersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MoviesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MoviesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(PersonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(SearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ByJsonButton, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(ByJsonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MoviesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MoviesButton)
                .addGap(18, 18, 18)
                .addComponent(PersonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PersonButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ByJsonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ByJsonButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPrincipal.setBackground(new java.awt.Color(204, 204, 255));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(597, 350));
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void setIconsToForms(){
        // Setando imagem na label de Filmes
        ImageIcon imgIcon = new ImageIcon("C:\\Users\\yuri.ramos\\Downloads\\JavaMovies-V4\\image_java_project\\Movie 3.png");
        Image image = imgIcon.getImage().getScaledInstance(this.MoviesLabel.getWidth(), this.MoviesLabel.getHeight(), Image.SCALE_SMOOTH);
        this.MoviesLabel.setIcon(new ImageIcon(image));
        
        // Setando imagem na label Person
        imgIcon = new ImageIcon("C:\\Users\\yuri.ramos\\Downloads\\JavaMovies-V4\\image_java_project\\User-blue.png");
        image = imgIcon.getImage().getScaledInstance(this.PersonLabel.getWidth(), this.PersonLabel.getHeight(), Image.SCALE_SMOOTH);
        this.PersonLabel.setIcon(new ImageIcon(image));
        
        // Setando imagem na label Person
        imgIcon = new ImageIcon("C:\\Users\\yuri.ramos\\Downloads\\JavaMovies-V4\\image_java_project\\Misc-Search-icon.png");
        image = imgIcon.getImage().getScaledInstance(this.SearchLabel.getWidth(), this.SearchLabel.getHeight(), Image.SCALE_SMOOTH);
        this.SearchLabel.setIcon(new ImageIcon(image));
        
        // Setando imagem na label By Json
        imgIcon = new ImageIcon("C:\\Users\\yuri.ramos\\Downloads\\JavaMovies-V4\\image_java_project\\favicon.png");
        image = imgIcon.getImage().getScaledInstance(this.ByJsonLabel.getWidth(), this.ByJsonLabel.getHeight(), Image.SCALE_SMOOTH);
        this.ByJsonLabel.setIcon(new ImageIcon(image));
 
    }
    
    private void MoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesButtonActionPerformed
        
        this.movies_panel = new MoviesPanel();
        
        this.jPanelPrincipal.add(this.movies_panel, "MoviesPanel");
        CardLayout card = (CardLayout) this.jPanelPrincipal.getLayout();
        card.show(this.jPanelPrincipal, "MoviesPanel");
        pack(); // reajusta a segunda Jpanel para caber na JPanelPrincipal //
        
    }//GEN-LAST:event_MoviesButtonActionPerformed

    private void PersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PersonButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        this.search_panel = new SearchPanel();
        
        this.jPanelPrincipal.add(this.search_panel, "SearchPanel");
        CardLayout card = (CardLayout) this.jPanelPrincipal.getLayout();
        card.show(this.jPanelPrincipal, "SearchPanel");
        pack(); // reajusta a segunda Jpanel para caber na JPanelPrincipal //
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ByJsonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByJsonButtonActionPerformed
        // TODO add your handling code here:
        this.by_json_panel = new ByJsonPanel();
        
        this.jPanelPrincipal.add(this.by_json_panel, "ByJsonPanel");
        CardLayout card = (CardLayout) this.jPanelPrincipal.getLayout();
        card.show(this.jPanelPrincipal, "ByJsonPanel");
        pack(); // reajusta a segunda Jpanel para caber na JPanelPrincipal //
       
    }//GEN-LAST:event_ByJsonButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ByJsonButton;
    private javax.swing.JLabel ByJsonLabel;
    private javax.swing.JButton MoviesButton;
    private javax.swing.JLabel MoviesLabel;
    private javax.swing.JButton PersonButton;
    private javax.swing.JLabel PersonLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel SearchLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables

    
}
