/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import java.awt.Color;
import java.awt.Image;
import java.awt.PopupMenu;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javamovies.DataBaseManager;
import javamovies.Titles;
import javax.imageio.ImageIO;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.border.Border;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author Yuri.Ramos
 */
public class MoviesPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form MoviesPanel
     */
    public MoviesPanel() {
        initComponents();
        InitMoviesPanel();
        InitComboBoxes();
        CreatePoputRightClick();
    }

    void InitComboBoxes() {
        // setando valores default no comboBox para gênero //
        this.GenreComboBox.addItem("--");
        this.GenreComboBox.addItem("Action");
        this.GenreComboBox.addItem("Adventure");
        this.GenreComboBox.addItem("Comedy");
        this.GenreComboBox.addItem("Documentary");
        this.GenreComboBox.addItem("Drama");
        this.GenreComboBox.addItem("Horror");
        this.GenreComboBox.addItem("Romance");
        this.GenreComboBox.addItem("Sci-Fi");
        this.GenreComboBox.addItem("Thriller");
        
        // setando valores no comboBox de ano //
        for(int i = 2017; i >= 1900; i--){
            this.YearComboBox.addItem(Integer.toString(i));
        }
    }
    
    // reseta elementos da tela de inclusão de Titulos //
    void InitMoviesPanel(){
        this.DirectorTextField.setText("");
        this.ImageCoverLabel.setText("");
        this.ImageCoverTextField.setText("");
        this.ImdbScoreTextField.setText("");
        this.TitleTextField.setText("");
        this.WriterTextField.setText("");
        
        // setando borda preta em torno da Label //
        Border border = BorderFactory.createLineBorder(Color.BLACK);
        this.ImageCoverLabel.setBorder(border);
        this.ImageCoverLabel.setIcon(null);
        
        ImageIcon imgIcon = new ImageIcon("C:\\Users\\yuri.ramos\\Downloads\\JavaMovies-V4\\image_java_project\\IMDb-Icon.png");
        //Image image = imgIcon.getImage().getScaledInstance(this.ImdbLogoLabel.getWidth(), this.ImdbLogoLabel.getHeight(), Image.SCALE_SMOOTH);
        Image image = imgIcon.getImage().getScaledInstance(45, 35, Image.SCALE_SMOOTH);
        this.ImdbLabel.setIcon(new ImageIcon(image));
        this.ImdbLabel.setText("");
    }
    
    boolean isDouble(String str){
        
        if(this.ImdbScoreTextField.getText().compareTo("") != 0) {
            try {
                Double.parseDouble(str);
                return true;
            } catch (NumberFormatException e) {
                return false;
            }
        }
        else{
            return true; // se for espaço, deve retornar verdadeiro //
        }
    }
    
    void CreatePoputRightClick() {
        // campo TITLE //
        JPopupMenu popup = new JPopupMenu();
        JMenuItem item = new JMenuItem(new DefaultEditorKit.CutAction());
        item.setText("Cut");
        popup.add(item);
        item = new JMenuItem(new DefaultEditorKit.CopyAction());
        item.setText("Copy");
        popup.add(item);
        item = new JMenuItem(new DefaultEditorKit.PasteAction());
        item.setText("Paste");
        popup.add(item);
        
        this.TitleTextField.setComponentPopupMenu(popup);
        this.DirectorTextField.setComponentPopupMenu(popup);
        this.ImageCoverTextField.setComponentPopupMenu(popup);
        this.ImdbScoreTextField.setComponentPopupMenu(popup);
        this.WriterTextField.setComponentPopupMenu(popup);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ImageCoverLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TitleTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DirectorTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        WriterTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ImdbLabel = new javax.swing.JLabel();
        ImdbScoreTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ImageCoverTextField = new javax.swing.JTextField();
        ImageCoverSendButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        GenreComboBox = new javax.swing.JComboBox<>();
        YearComboBox = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        MsgErroLabel = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Add Titles");

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setText("Title:");

        TitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Director:");

        DirectorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectorTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Writer: ");

        WriterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriterTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Genre:");

        ImdbLabel.setText("Imdb Score:");

        ImdbScoreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImdbScoreTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Image Cover (url):");

        ImageCoverTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageCoverTextFieldActionPerformed(evt);
            }
        });

        ImageCoverSendButton.setText("Send");
        ImageCoverSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageCoverSendButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Release Year:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WriterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(GenreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImageCoverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImageCoverSendButton))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ImdbLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImdbScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DirectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WriterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(GenreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImdbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImdbScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImageCoverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImageCoverSendButton)))
        );

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        MsgErroLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MsgErroLabel.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MsgErroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ImageCoverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ImageCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(MsgErroLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleTextFieldActionPerformed

    private void DirectorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirectorTextFieldActionPerformed

    private void WriterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriterTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WriterTextFieldActionPerformed

    private void ImdbScoreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImdbScoreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImdbScoreTextFieldActionPerformed

    private void ImageCoverTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageCoverTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImageCoverTextFieldActionPerformed

    private void ImageCoverSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageCoverSendButtonActionPerformed
        // TODO add your handling code here:
        String url_input;
        url_input = this.ImageCoverTextField.getText();

        Image image = null;
        URL url = null;
        try {
            url = new URL(url_input);
            image = ImageIO.read(url);
        } catch (MalformedURLException ex) {
            System.out.println("Malformed URL");
        } catch (IOException iox) {
            System.out.println("Can not load file");
        }

        ImageIcon imgIcon = new ImageIcon(image);
        // instrução abaixo realiza o ajuste da imagem para o alinhamento da JLabel
        Image img = imgIcon.getImage().getScaledInstance(this.ImageCoverLabel.getWidth(), this.ImageCoverLabel.getHeight(), Image.SCALE_SMOOTH);
        this.ImageCoverLabel.setIcon(new ImageIcon(img));

    }//GEN-LAST:event_ImageCoverSendButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        Titles title = new Titles();
        // recuperando valores inseridos nos campos da tela //
        title.setTitleName(this.TitleTextField.getText());
        title.setDirector(this.DirectorTextField.getText());
        title.setWriter(this.WriterTextField.getText());
        title.setImageCover(this.ImageCoverTextField.getText());
        title.setReleaseYear(Integer.parseInt(this.YearComboBox.getSelectedItem().toString()));
        
        // Validando campo IMDB_SCORE //
        // se dado NÃO for double //
        if(!isDouble(this.ImdbScoreTextField.getText())){ 
            System.out.println(isDouble(this.ImdbScoreTextField.getText()));
            this.MsgErroLabel.setText("Campo IMDB com formato inválido!");
        }
        else{
            this.MsgErroLabel.setText("");
        }
        // precisa ser posto aqui para que barre o salvamento no banco //
        if(this.ImdbScoreTextField.getText().compareTo("") != 0){
            title.setImdbScore(Double.parseDouble(this.ImdbScoreTextField.getText()));
        }
        
        // verificando se o valor incluído está entre 0 e 10 //
        // Caso não esteja:
        if(title.getImdbScore() < 0.0 || title.getImdbScore() > 10.0) {
            this.MsgErroLabel.setText("Nota IMDB deve ser entre 0 e 10!");
            Double.parseDouble(""); // força erro, impedindo inserção do campo no banco //
        }
        
        // verificando valores de Gênero //
        // se item for o primeiro do combo, setar como nulo para o Banco //
        if(this.GenreComboBox.getSelectedItem().toString().compareTo("--") == 0) {
            title.setGenre(null);
        }
        else {
            title.setGenre(this.GenreComboBox.getSelectedItem().toString());
        }
        
        DataBaseManager dataBase = new DataBaseManager();
        // abrindo conexão com o banco de dados //
        dataBase.OpenConnectionDataBase();
        
        // verificando se Título já existe na base de dados //
        // se existir, retorna true para a condição //
        if(!dataBase.VerifyIfExistTitle(title.getTitleName(), title.getDirector())){
            // se nao existir, executar querys //
            dataBase.ExecuteQueryInsert(title);
            // caixa de diálogo //
            JOptionPane.showMessageDialog(null, "Your Title was Included!");
            InitMoviesPanel(); // limpa tela de inclusão após registro ser salvo //
        }
        else {
            this.MsgErroLabel.setText("Title Already Exist for this Director!");
        }
        
        dataBase.CloseConnection();
    }//GEN-LAST:event_SaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DirectorTextField;
    private javax.swing.JComboBox<String> GenreComboBox;
    private javax.swing.JLabel ImageCoverLabel;
    private javax.swing.JButton ImageCoverSendButton;
    private javax.swing.JTextField ImageCoverTextField;
    private javax.swing.JLabel ImdbLabel;
    private javax.swing.JTextField ImdbScoreTextField;
    private javax.swing.JLabel MsgErroLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField TitleTextField;
    private javax.swing.JTextField WriterTextField;
    private javax.swing.JComboBox<String> YearComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void addSeparator() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
