/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.BorderLayout;
import java.awt.Image;
import javamovies.Titles;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Yuri.Ramos
 */
public class TitleListPanel extends javax.swing.JPanel {

    private Titles title;
    
    /**
     * Creates new form titleListPanel
     */
    public TitleListPanel() {
        initComponents();
        
        ImageIcon imgIcon = new ImageIcon("C:\\Users\\yuri.ramos\\Downloads\\JavaMovies-V4\\image_java_project\\IMDb-Icon.png");
        //Image image = imgIcon.getImage().getScaledInstance(this.ImdbLogoLabel.getWidth(), this.ImdbLogoLabel.getHeight(), Image.SCALE_SMOOTH);
        Image image = imgIcon.getImage().getScaledInstance(40, 30, Image.SCALE_SMOOTH);
        this.ImdbLogoLabel.setIcon(new ImageIcon(image));
        
    }
    
    public void setTitles(Titles t) {
        this.title = t;
    }
    public Titles getTitles() {
        return this.title;
    }
    
    void setPanelAttributes(){
        
        this.DirectorLabel.setText(this.title.getDirector());
        this.GenreLabel.setText(this.title.getGenre());
        this.ImdbScoreLabel.setText(Double.toString(this.title.getImdbScore()));
        this.TitleLabel.setText(this.title.getTitleName());
        this.WriterLabel.setText(this.title.getWriter());
        this.YearLabel.setText("(" + Integer.toString(this.title.getReleaseYear()) + ")");
        
        // instrução abaixo realiza o ajuste da imagem para o alinhamento da JLabel
        Image img = this.title.getImage().getImage().getScaledInstance(102, 157, Image.SCALE_SMOOTH);
        this.ImageCoverLabel.setIcon(new ImageIcon(img));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageCoverLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        DirectorLabel = new javax.swing.JLabel();
        WriterLabel = new javax.swing.JLabel();
        YearLabel = new javax.swing.JLabel();
        ImdbLogoLabel = new javax.swing.JLabel();
        ImdbScoreLabel = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ImageCoverLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TitleLabel.setText("Title");

        DirectorLabel.setText("director");

        WriterLabel.setText("writer");

        YearLabel.setText("Year:");

        ImdbLogoLabel.setText("jLabel4");
        ImdbLogoLabel.setMaximumSize(new java.awt.Dimension(40, 20));
        ImdbLogoLabel.setMinimumSize(new java.awt.Dimension(40, 20));
        ImdbLogoLabel.setPreferredSize(new java.awt.Dimension(40, 20));

        ImdbScoreLabel.setText("ImdbScore");

        GenreLabel.setText("genre");

        jLabel1.setText("Director:");

        jLabel2.setText("Writer: ");

        jButton1.setText("detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImdbLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ImdbScoreLabel))
                    .addComponent(GenreLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YearLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DirectorLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(WriterLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TitleLabel)
                            .addComponent(YearLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenreLabel)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DirectorLabel)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(WriterLabel)
                                    .addComponent(jLabel2))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ImdbLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ImdbScoreLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1))))
                    .addComponent(ImageCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        NativeInterface.open();
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                MovieDetailFrame movieDetail = new MovieDetailFrame(title);
                movieDetail.setResizable(false);
                movieDetail.setLocationRelativeTo(null); // posiciona a tela no centro do monitor
                movieDetail.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                movieDetail.TrailerPanel.add(getBrowser(), BorderLayout.CENTER);
                movieDetail.setVisible(true);
            }
        });
        NativeInterface.runEventPump();
        // don't forget to properly close native components
        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            @Override
            public void run() {
                NativeInterface.close();
            }
        }));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public static JPanel getBrowser() {
        JPanel webBrowserPanel = new JPanel(new BorderLayout());
        JWebBrowser webBrowser = new JWebBrowser();
        webBrowserPanel.add(webBrowser, BorderLayout.CENTER);
        webBrowser.setBarsVisible(false);
        webBrowser.navigate("https://www.youtube.com/embed/gCcx85zbxz4?fs=1");
        
        return webBrowserPanel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DirectorLabel;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JLabel ImageCoverLabel;
    private javax.swing.JLabel ImdbLogoLabel;
    private javax.swing.JLabel ImdbScoreLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel WriterLabel;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
